# ML Pipeline Preparation
Follow the instructions below to help you create your ML pipeline.
### 1. Import libraries and load data from database.
- Import Python libraries
- Load dataset from database with [`read_sql_table`](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_sql_table.html)
- Define feature and target variables X and Y

In [1]:
# import libraries
import re
import numpy as np
import pandas as pd

import nltk
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
nltk.download('wordnet')
nltk.download('punkt')
nltk.download('stopwords')

from sqlalchemy import create_engine

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline, FeatureUnion
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer
from sklearn.multioutput import MultiOutputClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score, precision_score, recall_score, f1_score,make_scorer
from sklearn.metrics import confusion_matrix
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier

import pickle

import warnings
warnings.simplefilter('ignore')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\ddasil28\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\ddasil28\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ddasil28\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [2]:
# load data from database
engine = create_engine('sqlite:///./data/DisasterResponseData.db')
df = pd.read_sql('select * from DisasterResponse', engine)
X = df['message']
Y = df.iloc[:, 4:]

### 2. Write a tokenization function to process your text data

In [3]:
def tokenize(text):
    text = re.sub(r"[^a-zA-Z0-9]", " ", text)
    text = text.lower()

    tokens = word_tokenize(text)
    # Remove stop words
    tokens = [w for w in tokens if w not in stopwords.words("english")]
    lemmatizer = WordNetLemmatizer()

    clean_tok = []
    for tok in tokens:
        clean_tok.append(lemmatizer.lemmatize(tok).strip())

    return clean_tok

### 3. Build a machine learning pipeline
This machine pipeline should take in the `message` column as input and output classification results on the other 36 categories in the dataset. You may find the [MultiOutputClassifier](http://scikit-learn.org/stable/modules/generated/sklearn.multioutput.MultiOutputClassifier.html) helpful for predicting multiple target variables.

In [4]:
pipeline = Pipeline([
    ('vect', CountVectorizer(tokenizer=tokenize)),
    ('tfidf', TfidfTransformer()),
    ('clf', MultiOutputClassifier(RandomForestClassifier(), n_jobs=-1))
])

### 4. Train pipeline
- Split data into train and test sets
- Train pipeline

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, random_state = 42)

In [5]:
pipeline.fit(X_train, Y_train)

Pipeline(steps=[('vect',
                 CountVectorizer(tokenizer=<function tokenize at 0x00000232A1EEF790>)),
                ('tfidf', TfidfTransformer()),
                ('clf',
                 MultiOutputClassifier(estimator=RandomForestClassifier()))])

### 5. Test your model
Report the f1 score, precision and recall for each output category of the dataset. You can do this by iterating through the columns and calling sklearn's `classification_report` on each.

In [6]:
target_names = Y_test.columns

In [7]:
y_pred = pipeline.predict(X_test)

In [8]:
# Calculate the accuracy for each one
for i in range(len(target_names)):
    print('Target category {}: {} '.format(i, target_names[i]))
    print(classification_report(Y_test.iloc[:, i].values, y_pred[:, i]))
    print('Confusion Matrix: \n {} \n\n'.format(confusion_matrix(y_pred[:, i], Y_test.iloc[:, i])))
    print('Accuracy {}\n\n'.format(accuracy_score(Y_test.iloc[:, i].values, y_pred[:, i])))

Target category 0: related 
              precision    recall  f1-score   support

           0       0.69      0.41      0.51      1563
           1       0.83      0.94      0.88      4944
           2       0.35      0.38      0.36        47

    accuracy                           0.81      6554
   macro avg       0.62      0.58      0.59      6554
weighted avg       0.80      0.81      0.79      6554

Confusion Matrix: 
 [[ 635  278    1]
 [ 914 4646   28]
 [  14   20   18]] 


Accuracy 0.808513884650595


Target category 1: request 
              precision    recall  f1-score   support

           0       0.90      0.98      0.94      5443
           1       0.82      0.48      0.60      1111

    accuracy                           0.89      6554
   macro avg       0.86      0.73      0.77      6554
weighted avg       0.89      0.89      0.88      6554

Confusion Matrix: 
 [[5327  580]
 [ 116  531]] 


Accuracy 0.8938053097345132


Target category 2: offer 
              precision

Confusion Matrix: 
 [[6407  143]
 [   0    4]] 


Accuracy 0.9781812633506256


Target category 23: tools 
              precision    recall  f1-score   support

           0       0.99      1.00      1.00      6511
           1       0.00      0.00      0.00        43

    accuracy                           0.99      6554
   macro avg       0.50      0.50      0.50      6554
weighted avg       0.99      0.99      0.99      6554

Confusion Matrix: 
 [[6511   43]
 [   0    0]] 


Accuracy 0.9934391211473909


Target category 24: hospitals 
              precision    recall  f1-score   support

           0       0.99      1.00      1.00      6498
           1       0.00      0.00      0.00        56

    accuracy                           0.99      6554
   macro avg       0.50      0.50      0.50      6554
weighted avg       0.98      0.99      0.99      6554

Confusion Matrix: 
 [[6498   56]
 [   0    0]] 


Accuracy 0.9914555996338114


Target category 25: shops 
              precisi

In [9]:
#Clear view droped the first column multiclass and multilabeled
print(classification_report(Y_test.iloc[:, 1:].values, np.array([x[1:] for x in y_pred]), target_names = target_names[1:]))

                        precision    recall  f1-score   support

               request       0.82      0.48      0.60      1111
                 offer       0.00      0.00      0.00        33
           aid_related       0.75      0.69      0.72      2670
          medical_help       0.62      0.08      0.14       535
      medical_products       0.76      0.08      0.15       344
     search_and_rescue       0.80      0.03      0.05       159
              security       0.25      0.01      0.02       116
              military       0.61      0.07      0.13       200
           child_alone       0.00      0.00      0.00         0
                 water       0.86      0.40      0.54       418
                  food       0.88      0.58      0.70       745
               shelter       0.82      0.36      0.50       581
              clothing       0.85      0.11      0.20        98
                 money       0.80      0.06      0.11       133
        missing_people       1.00      

### 6. Improve your model
Use grid search to find better parameters. 

In [10]:
pipeline.get_params()

{'memory': None,
 'steps': [('vect',
   CountVectorizer(tokenizer=<function tokenize at 0x00000232A1EEF790>)),
  ('tfidf', TfidfTransformer()),
  ('clf', MultiOutputClassifier(estimator=RandomForestClassifier()))],
 'verbose': False,
 'vect': CountVectorizer(tokenizer=<function tokenize at 0x00000232A1EEF790>),
 'tfidf': TfidfTransformer(),
 'clf': MultiOutputClassifier(estimator=RandomForestClassifier()),
 'vect__analyzer': 'word',
 'vect__binary': False,
 'vect__decode_error': 'strict',
 'vect__dtype': numpy.int64,
 'vect__encoding': 'utf-8',
 'vect__input': 'content',
 'vect__lowercase': True,
 'vect__max_df': 1.0,
 'vect__max_features': None,
 'vect__min_df': 1,
 'vect__ngram_range': (1, 1),
 'vect__preprocessor': None,
 'vect__stop_words': None,
 'vect__strip_accents': None,
 'vect__token_pattern': '(?u)\\b\\w\\w+\\b',
 'vect__tokenizer': <function __main__.tokenize(text)>,
 'vect__vocabulary': None,
 'tfidf__norm': 'l2',
 'tfidf__smooth_idf': True,
 'tfidf__sublinear_tf': False,


In [ ]:
parameters = {
    #'vect__ngram_range': ((1, 1), (1, 2))
    #, 'vect__max_df': (0.5, 0.75, 1.0)
    #, 'tfidf__use_idf': (True, False)
    'clf__estimator__n_estimators': [50, 100]
    , 'clf__estimator__min_samples_split': [2, 3, 5]
}

pipeline_cv = GridSearchCV(pipeline, param_grid = parameters, cv=3, scoring='accuracy', n_jobs = -1)

%time pipeline_cv.fit(X_train, Y_train)

In [ ]:
print(pipeline_cv.best_params_)
print(pipeline_cv.best_score_)
print(pipeline_cvl.best_estimator_)
print(pipeline_cv.grid_scores_)

In [ ]:
#building new model
optimised_model = pipeline_cv.best_estimator_

### 7. Test your model
Show the accuracy, precision, and recall of the tuned model.  

Since this project focuses on code quality, process, and  pipelines, there is no minimum performance metric needed to pass. However, make sure to fine tune your models for accuracy, precision and recall to make your project stand out - especially for your portfolio!

In [ ]:
optimised_model.fit(X_train, Y_train)
print('Best Parameters:', pipeline_cv.best_params_)

In [ ]:
y_pred = optimised_model.predict(X_test)
print(classification_report(Y_test.iloc[:, 1:].values, np.array([x[1:] for x in y_pred]), target_names = target_names[1:]))

### 8. Try improving your model further. Here are a few ideas:
* try other machine learning algorithms
* add other features besides the TF-IDF

In [ ]:
pipeline = Pipeline([
    ('vect', CountVectorizer(tokenizer = tokenize)),
    ('tfidf', TfidfTransformer()),
    ('clf', MultiOutputClassifier(KNeighborsClassifier(), n_jobs=-1))
])

parameters_kn = {'tfidf__use_idf':[True, False],
                 'clf__estimator__weights':['uniform','distance'],
                 'clf__estimator__leaf_size':[25,35]
                }
cv = GridSearchCV(pipeline, param_grid = parameters_kn, verbose=5, n_jobs=-1)

np.random.seed(42)

kn_model = cv.fit(X_train, Y_train)

In [ ]:
print(kn_model.best_params_)
print(cv.best_score_)

### 9. Export your model as a pickle file

In [ ]:
with open('./model/classifier.pkl', 'wb') as file:
    pickle.dump(optimised_model, file)

### 10. Use this notebook to complete `train.py`
Use the template file attached in the Resources folder to write a script that runs the steps above to create a database and export a model based on a new dataset specified by the user.